# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  services:
    default: frontend,history,matching,worker
    description: |
      A comma separated list of Temporal services to run. Temporal components
      can be either run in a single container or spread across multiple
      containers, which allows to independently scale each component.
    type: string
  log-level:
    default: info
    description: Temporal server logging level.
    type: string
  external-hostname:
    description: |
        The DNS listing used for external connections. Will default to the name of the deployed
        application.
    default: ""
    type: string
  tls-secret-name:
    description: |
        Name of the k8s secret which contains the TLS certificate to be used by ingress.
    default: "temporal-tls"
    type: string
  auth-enabled:
    description: |
        Specifies whether authorization should be enabled through OpenFGA.
    default: false
    type: boolean
