# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  services:
    default: frontend,history,matching,worker
    description: |
      A comma-separated list of Temporal services to run. Temporal components
      can be either run in a single container or spread across multiple
      containers, which allows to independently scale each component.
    type: string
  num-history-shards:
    default: 0
    description: |
      The number of concurrent database operations that can occur for a Temporal Cluster.
      This value can only be set once at deployment time. Setting the value after it has
      already been set will send the charm into a blocked state until it is set back to the
      original value.

      This value must be consistent across all components if using a scaled deployment.
    type: int
  log-level:
    default: info
    description: Temporal server logging level.
    type: string
  external-hostname:
    description: |
        The DNS listing used for external connections. Will default to the name of the deployed
        application.
    default: ""
    type: string
  tls-secret-name:
    description: |
        Name of the k8s secret which contains the TLS certificate to be used by ingress.
    default: "temporal-tls"
    type: string
  auth-enabled:
    description: |
        Specifies whether authorization should be enabled through OpenFGA.
    default: false
    type: boolean
  auth-google-client-id:
    description: |
        The client ID of the Google OAuth project used for authentication.
        This will be used in authorization requests to verify the origin of the
        OAuth2 token. While it is an optional field, it is recommended to set it
        for added security.
    default: ""
    type: string
  auth-admin-groups:
    description: |
        A comma-separated list of groups with read-access to all namespaces.
        This group must be created in the OpenFGA store, and the corresponding
        users added to it as members.
    default: ""
    type: string
  auth-open-access-namespaces:
    description: |
        A comma-separated list of namespaces which will be visible to all 
        authenticated users.
    default: ""
    type: string
