# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
minversion = 4.10
requires = tox-uv>=1.13
envlist = fmt, lint, unit, static, coverage-report
skipsdist = True
skip_missing_interpreters = True
max-line-length = 120

[vars]
src_path = {toxinidir}/src/
tst_path = {toxinidir}/tests/
all_path = {[vars]src_path} {[vars]tst_path}

[testenv]
package = editable
setenv =
  PYTHONPATH = {toxinidir}:{toxinidir}/lib:{[vars]src_path}
  PYTHONBREAKPOINT = ipdb.set_trace
  PY_COLORS = 1
passenv =
  PYTHONPATH
  CHARM_BUILD_DIR
  MODEL_SETTINGS

[testenv:fmt]
description = Format the code
deps = .[fmt]
commands =
  isort {[vars]src_path} {[vars]tst_path}
  black {[vars]src_path} {[vars]tst_path}

[testenv:lint]
description = Lint the code
deps = .[lint]
commands =
  pydocstyle {[vars]src_path}
  codespell {toxinidir} --skip {toxinidir}/.git --skip {toxinidir}/.tox \
    --skip {toxinidir}/build --skip {toxinidir}/lib --skip {toxinidir}/venv \
    --skip {toxinidir}/.mypy_cache --skip {toxinidir}/icon.svg --skip {toxinidir}/uv.lock*
  pflake8 {[vars]src_path} {[vars]tst_path}
  isort --check-only --diff {[vars]src_path} {[vars]tst_path}
  black --check --diff {[vars]src_path} {[vars]tst_path}
  mypy {[vars]all_path} --ignore-missing-imports --follow-imports=skip --install-types --non-interactive
  pylint {[vars]all_path} --disable=E0401,W1203,W0613,W0718,R0903,W1514,C0103,R0913,C0301,W0212,R0902,C0104,W0640,R0801,W0511,R0914,R0912,W0719,R0917

[testenv:unit]
description = Run unit tests
deps = .[unit]
commands =
  coverage run --source={[vars]src_path} \
    -m pytest --ignore={[vars]tst_path}integration -v --tb native -s {posargs}
  coverage report

[testenv:coverage-report]
description = Create test coverage report
deps = coverage[toml]>=7.5.0
commands =
  coverage report

[testenv:static]
description = Run static analysis tests
deps =
  bandit[toml]
commands =
  bandit -c {toxinidir}/pyproject.toml -r {[vars]src_path} {[vars]tst_path}

[testenv:integration]
description = Run integration tests
deps = .[integration]
commands =
  pytest --tb native --ignore={[vars]tst_path}unit --ignore={[vars]tst_path}scenario --log-cli-level=INFO -s {posargs}
