#!/bin/sh
dispatch_path="$(dirname $(realpath $0))"
venv_bin_path="${dispatch_path}/venv/bin"
python_path="${venv_bin_path}/python"
if [ ! -e "${python_path}" ]; then
    mkdir -p "${venv_bin_path}"
    ln -s $(which python3) "${python_path}"
fi

# Add charm lib and source directories to PYTHONPATH so the charm can import
# libraries and its own modules as expected.
export PYTHONPATH="${dispatch_path}/lib:${dispatch_path}/src"

# Add the charm's lib and usr/lib directories to LD_LIBRARY_PATH, allowing
# staged packages to be discovered by the dynamic linker.
export LD_LIBRARY_PATH="${dispatch_path}/usr/lib:${dispatch_path}/lib:${dispatch_path}/usr/lib/$(uname -m)-linux-gnu"

if [ ! -d "${dispatch_path}/venv/lib" ]; then
    echo "[dispatch] Re-installing charm dependencies into venv..."
    "${dispatch_path}/venv/bin/python" -m pip install --no-cache-dir --no-deps --upgrade "${dispatch_path}"
fi

exec "${python_path}" "${dispatch_path}/src/charm.py"
