name: Integration tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_call:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      provider: k8s
      use-canonical-k8s: true
      channel: 1.33-classic/stable
      charmcraft-channel: latest/stable
      modules: '["test_charm.py", "test_auth.py", "test_scaling.py", "test_server_upgrade.py", "test_upgrades.py", "test_pgbouncer.py", "test_host_info.py"]'
      juju-channel: 3.6/stable
      self-hosted-runner: true
      self-hosted-runner-label: large
      self-hosted-runner-arch: x64
      self-hosted-runner-image: noble
      test-timeout: 35
