name: Integration tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_call:

jobs:
  integration-tests:
    uses: arjun11-malik/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      provider: k8s
      use-canonical-k8s: true
      channel: edge
      modules: '["test_traefik_ingress.py", "test_charm.py", "test_auth.py", "test_scaling.py", "test_server_upgrade.py", "test_upgrades.py"]'
      juju-channel: 3.6/stable
      self-hosted-runner: false
