name: Terraform checks

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  pull_request:
  workflow_call:

jobs:
  pull-request-terraform-checks:
    name: PR Terraform checks
    uses: canonical/workflows-team/.github/workflows/terraform.yaml@main
