#Force github to re-register workflow
name: Tiobe TiCS Analysis

on:
  workflow_dispatch:  # Manual trigger
  pull_request:
  schedule:
    - cron: '0 4 * * 1'  # Every Monday at 4 AM UTC

jobs:
  tics:
    name: TiCS
    uses: canonical/observability/.github/workflows/charm-tiobe-scan.yaml@v1
    secrets: inherit
