name: Tiobe TiCS Analysis

on:
    pull_request: #triggering workflow
    workflow_dispatch:
    schedule:
    - cron: "17 2 * * 1"  # Runs at 2:17 UTC every Monday

jobs:
    tics:
        name: TiCs
        # Only run if we have access to secrets.
        if: github.event_name != 'pull_request' || github.repository == github.event.pull_request.head.repo.full_name
        uses: canonical/observability/.github/workflows/charm-tiobe-scan.yaml@main
        with: 
            coverage-folder: ".cover"
        secrets: inherit
